name: trump-archive
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytube>=12.1.0
  - google-api-python-client>=2.0.0
  - openai>=0.27.0
  - langchain>=0.0.267
  - whisper>=1.0.0
  - transformers>=4.30.0
  - numpy>=1.24.0
  - tqdm>=4.65.0
  - pydub>=0.25.1
  - pip:
      - python-dotenv>=1.0.0ssd